package:
  name: easypbr
  version: 1.0.0

build:
  number: 0
  # script_env:
    # - CC
    # - CXX
  # rpaths:
    # - lib/ #we will look for dynamically loaded shared libraries like easypbr_cpp in $PREFIX/lib. a post-link.sh script will copy the shared lib there for easy finding
    # - ./ 
    # - lib/python3.6/site-packages


source:
  path: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}	     # [linux]
    - {{ cdt('mesa-libgl-devel') }}	     # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}	     # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}	     # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}	     # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}	     # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]

    # - python 
    - setuptools
    - cmake >=3.14.0
    # - glfw
    # - boost
    # - pcl
    # - opencv # [win]
    # - libopencv # [linux]
    # - eigen 
  host: #THINGS DEFINED IN HOST REQUIREMENTS SHOULD NOT BE IN BUILD
    - python
    - glfw
    - boost
    - pcl
    - opencv # [win]
    - libopencv # [linux]
    - eigen

  run:
    - python
    - glfw
    - pcl
    - opencv # [win]
    - libopencv # [linux]
    - eigen

test:
  imports:
    - easypbr

# outputs:
#   - name: easypbr_cpp
#     script: move_files_cpp.sh
#     # files:
#       # - CMakeLists.txt
#       # - build/lib.linux-x86_64-3.6/libeasypbr_cpp.so
#       # - lib.linux-x86_64-3.6/libeasypbr_cpp.so
#       # - libeasypbr_cpp.so
#       # - *.*

  # - name: easypbr_py
#   #   script: move_files_py.sh
#   #   # -files:
#   #     # - build/lib.linux-x86_64-3.6/cmake_example.cpython-36m-x86_64-linux-gnu.so
#   #   requirements:
#   #     build:
#   #       - easypbr_cpp
#   #     host: 
#   #       - easypbr_cpp
#   #     run:
#   #       - easypbr_cpp
#     # test:
#     #   imports:
#     #     - easypbr_py

about:
  summary: An example project built with pybind11.
  license_file: LICENSE
